spring:
  security:
    user:
      name: demo
      password: demo
  datasource:
    url: jdbc:h2:file:./demodb
    username: sa
    password: sa
  h2:
    console:
      enabled: true
      path: /h2-console


# disable Whitelabel Error Page
server:
  error:
    whitelabel:
      enabled: false